/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'Maciej' at '11/18/16 3:30 PM' with Gradle 2.14.1
 *
 * @author Maciej, @date 11/18/16 3:30 PM
 */
public class Library {


    public boolean someLibraryMethod() {
        return true;
    }

    public void breakTherules(String ruleBreaker) {
        if ("rule breaker" == ruleBreaker) {
            System.out.println("Breaking some sonar rules");
        }
        //thread.run();
    }

    Thread thread;
}
