/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'Maciej' at '11/18/16 3:30 PM' with Gradle 2.14.1
 *
 * @author Maciej, @date 11/18/16 3:30 PM
 */
public class Library {

    final Thread thread = null;
    
    public boolean someLibraryMethod() {
        return true;
    }

    public String breakTherules(String ruleBreaker) {
        if ("rule breaker" == ruleBreaker) {
            System.out.println("Breaking some sonar rules");
            thread.run(); // I want the metics to fail finally!!!
        }

        return ruleBreaker;
    }
    
    public boolean string_compare() {
        return "test" == new String();
    }
    
    
    public String PleaseBreakSomeMore(int a) {
        a = 5;
        // no change
        return breakTherules("" + a);
    }
}
