import static org.junit.Assert.assertTrue;

import org.junit.Assert;
import org.junit.Test;

/*
 * This Java source file was auto generated by running 'gradle init --type java-library'
 * by 'Maciej' at '11/18/16 3:30 PM' with Gradle 2.14.1
 *
 * @author Maciej, @date 11/18/16 3:30 PM
 */
public class LibraryTest {
    @Test 
    public void testSomeLibraryMethod() {
        Library classUnderTest = new Library();
        assertTrue("someLibraryMethod should return 'true'", classUnderTest.someLibraryMethod());
    }
    
    @Test
    public void dontfail() {
        new Library().breakTherules("ruleBreaker");
        //Assert.fail("just fail here");
    }
    
    @Test
    public void fail() {
        Assert.fail("just fail here");
    }
}
